#!/bin/bash

# Artifact Vault Client Configuration Script
# Configures apt, pip, or docker to use Artifact Vault as a proxy

set -e  # Exit on any error

SCRIPT_NAME="$(basename "$0")"
VERSION="1.0.0"

# Default values
ARTIFACT_VAULT_URL=""
APPLICATION=""
BACKUP_SUFFIX=".artifact-vault-backup"
VERBOSE=false
DRY_RUN=false

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

nosudo() {
    echo "Error: This script must be run as root or with 'sudo' installed."
    echo "Tried to run: sudo $*"
    exit 1
}

if [ $EUID -eq 0 ]; then
    SUDO_CMD=""
else
    if ! sudo -n true 2>/dev/null; then
        SUDO_CMD="sudo"
    else
        SUDO_CMD="nosudo"
    fi
fi

# Print functions
print_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1" >&2
}

print_verbose() {
    if [ "$VERBOSE" = true ]; then
        echo -e "${BLUE}[VERBOSE]${NC} $1"
    fi
}

# Usage information
usage() {
    cat << EOF
Usage: $SCRIPT_NAME <application> <artifact-vault-url> [options]

Configure applications to use Artifact Vault as a proxy.

Arguments:
  application           Application to configure: apt, pip, or docker
  artifact-vault-url    URL of the Artifact Vault server (e.g., http://localhost:8080)

Options:
  -v, --verbose         Enable verbose output
  -n, --dry-run         Show what would be done without making changes
  -h, --help            Show this help message
  --version             Show version information

Examples:
  $SCRIPT_NAME apt http://localhost:8080
  $SCRIPT_NAME pip http://cache.company.com:8080
  $SCRIPT_NAME docker http://10.0.1.100:8080 --verbose
  $SCRIPT_NAME apt http://localhost:8080 --dry-run

Supported Applications:
  apt     - Configure APT to use Artifact Vault for Debian/Ubuntu packages
  pip     - Configure pip to use Artifact Vault for Python packages
  docker  - Configure Docker to use Artifact Vault as a registry mirror

EOF
}

# Version information
version() {
    echo "$SCRIPT_NAME version $VERSION"
}

# Validate URL format
validate_url() {
    local url="$1"
    if [[ ! "$url" =~ ^https?://[^/]+(:([0-9]+))?/?$ ]]; then
        print_error "Invalid URL format: $url"
        print_error "URL should be in format: http://hostname:port or https://hostname:port"
        return 1
    fi
    
    # Remove trailing slash if present
    ARTIFACT_VAULT_URL="${url%/}"
}

# Test connectivity to Artifact Vault
test_connectivity() {
    local url="$1"
    print_info "Testing connectivity to $url..."
    
    if command -v curl >/dev/null 2>&1; then
        if curl -s --connect-timeout 5 --max-time 10 "$url" >/dev/null 2>&1; then
            print_success "Successfully connected to Artifact Vault"
        else
            print_warning "Could not connect to Artifact Vault at $url"
            print_warning "Make sure the server is running and accessible"
        fi
    else
        print_warning "curl not available, skipping connectivity test"
    fi
}

# Create backup of a file
backup_file() {
    local file="$1"
    if [ -f "$file" ]; then
        local backup="${file}${BACKUP_SUFFIX}"
        if [ "$DRY_RUN" = true ]; then
            print_verbose "Would backup $file to $backup"
        else
            cp "$file" "$backup"
            print_verbose "Backed up $file to $backup"
        fi
    fi
}

# Configure APT
configure_apt() {
    local vault_url="$1"
    print_info "Configuring APT to use Artifact Vault..."
    
    # Check if we have sudo access
    if [ "$EUID" -ne 0 ] && ! sudo -n true 2>/dev/null; then
        print_error "APT configuration requires sudo access"
        return 1
    fi
    
    local apt_conf_dir="/etc/apt/apt.conf.d"
    local config_file="$apt_conf_dir/01-artifact-vault"
    
    # Create apt.conf.d directory if it doesn't exist
    if [ "$DRY_RUN" = true ]; then
        print_verbose "Would create directory $apt_conf_dir"
    else
        $SUDO_CMD mkdir -p "$apt_conf_dir"
    fi
    
    # Backup existing configuration if it exists
    if [ -f "$config_file" ]; then
        backup_file "$config_file"
    fi
    
    # Create APT proxy configuration
    local config_content="// Artifact Vault APT Proxy Configuration
// Generated by $SCRIPT_NAME on $(date)
// Artifact Vault URL: $vault_url

// Ubuntu/Debian main repositories
Acquire::http::proxy::archive.ubuntu.com \"$vault_url/apt/ubuntu/\";
Acquire::http::proxy::security.ubuntu.com \"$vault_url/apt/security/\";
Acquire::https::proxy::archive.ubuntu.com \"$vault_url/apt/ubuntu/\";
Acquire::https::proxy::security.ubuntu.com \"$vault_url/apt/security/\";

// Performance optimizations for cached repositories
Acquire::Queue-Mode \"host\";
Acquire::Max-Default-Age \"86400\";
"
    
    if [ "$DRY_RUN" = true ]; then
        print_verbose "Would create $config_file with proxy configuration"
        echo "Configuration content:"
        echo "$config_content"
    else
        echo "$config_content" | $SUDO_CMD tee "$config_file" > /dev/null
        print_success "APT configuration created at $config_file"
    fi
    
    print_info "To test the configuration, run: sudo apt update"
    print_info "To remove the configuration, delete: $config_file"
}

# Configure pip
configure_pip() {
    local vault_url="$1"
    print_info "Configuring pip to use Artifact Vault..."
    
    local pip_conf_dir
    local config_file
    
    # Determine pip configuration directory based on OS
    if [[ "$OSTYPE" == "darwin"* ]]; then
        # macOS
        pip_conf_dir="$HOME/Library/Application Support/pip"
        config_file="$pip_conf_dir/pip.conf"
    else
        # Linux and others
        pip_conf_dir="$HOME/.config/pip"
        config_file="$pip_conf_dir/pip.conf"
    fi
    
    # Create pip configuration directory if it doesn't exist
    if [ "$DRY_RUN" = true ]; then
        print_verbose "Would create directory $pip_conf_dir"
    else
        mkdir -p "$pip_conf_dir"
    fi
    
    # Backup existing configuration if it exists
    if [ -f "$config_file" ]; then
        backup_file "$config_file"
        print_warning "Existing pip configuration backed up"
    fi
    
    # Extract hostname from URL for trusted-host
    local hostname=$(echo "$vault_url" | sed 's/^http[s]*:\/\///' | cut -d: -f1 | cut -d/ -f1)
    
    # Create pip configuration
    local config_content="# Artifact Vault pip Configuration
# Generated by $SCRIPT_NAME on $(date)
# Artifact Vault URL: $vault_url

[global]
index-url = $vault_url/pypi/simple/
trusted-host = $hostname

[install]
trusted-host = $hostname
"
    
    if [ "$DRY_RUN" = true ]; then
        print_verbose "Would create $config_file with pip configuration"
        echo "Configuration content:"
        echo "$config_content"
    else
        echo "$config_content" > "$config_file"
        print_success "pip configuration created at $config_file"
    fi
    
    print_info "To test the configuration, run: pip install --dry-run requests"
    print_info "To remove the configuration, delete: $config_file"
}

# Configure Docker
configure_docker() {
    local vault_url="$1"
    print_info "Configuring Docker to use Artifact Vault..."
    
    local docker_daemon_file="/etc/docker/daemon.json"
    local docker_dir="/etc/docker"
    
    # Check if we have sudo access for system-wide configuration
    if [ "$EUID" -ne 0 ] && ! sudo -n true 2>/dev/null; then
        print_error "Docker configuration requires sudo access"
        return 1
    fi
    
    # Create docker directory if it doesn't exist
    if [ "$DRY_RUN" = true ]; then
        print_verbose "Would create directory $docker_dir"
    else
        $SUDO_CMD mkdir -p "$docker_dir"
    fi
    
    # Backup existing daemon.json if it exists
    if [ -f "$docker_daemon_file" ]; then
        backup_file "$docker_daemon_file"
        print_warning "Existing Docker daemon configuration backed up"
    fi
    
    # Create or update daemon.json
    local registry_mirror="$vault_url/dockerhub/"
    
    if [ -f "$docker_daemon_file" ] && [ "$DRY_RUN" = false ]; then
        # Existing daemon.json - try to merge configuration
        if command -v jq >/dev/null 2>&1; then
            # Use jq to merge configuration
            local temp_file=$(mktemp)
            jq --arg mirror "$registry_mirror" '. + {"registry-mirrors": [$mirror]}' "$docker_daemon_file" > "$temp_file"
            $SUDO_CMD mv "$temp_file" "$docker_daemon_file"
            print_success "Updated existing Docker daemon configuration"
        else
            print_warning "jq not available - creating new daemon.json (existing config may be lost)"
            local config_content="{
  \"registry-mirrors\": [\"$registry_mirror\"],
  \"log-driver\": \"json-file\",
  \"log-opts\": {
    \"max-size\": \"10m\",
    \"max-file\": \"3\"
  }
}"
            echo "$config_content" | sudo tee "$docker_daemon_file" > /dev/null
        fi
    else
        # Create new daemon.json
        local config_content="{
  \"registry-mirrors\": [\"$registry_mirror\"],
  \"log-driver\": \"json-file\",
  \"log-opts\": {
    \"max-size\": \"10m\",
    \"max-file\": \"3\"
  }
}"
        
        if [ "$DRY_RUN" = true ]; then
            print_verbose "Would create $docker_daemon_file with registry mirror configuration"
            echo "Configuration content:"
            echo "$config_content"
        else
            echo "$config_content" | $SUDO_CMD tee "$docker_daemon_file" > /dev/null
            print_success "Docker daemon configuration created at $docker_daemon_file"
        fi
    fi
    
    print_info "Docker daemon needs to be restarted for changes to take effect:"
    print_info "  sudo systemctl restart docker"
    print_info "To test the configuration, run: docker pull hello-world"
    print_info "To remove the configuration, edit or delete: $docker_daemon_file"
}

# Main configuration function
configure_application() {
    local app="$1"
    local url="$2"
    
    case "$app" in
        "apt")
            configure_apt "$url"
            ;;
        "pip")
            configure_pip "$url"
            ;;
        "docker")
            configure_docker "$url"
            ;;
        *)
            print_error "Unsupported application: $app"
            print_error "Supported applications: apt, pip, docker"
            return 1
            ;;
    esac
}

# Parse command line arguments
parse_args() {
    while [[ $# -gt 0 ]]; do
        case $1 in
            -h|--help)
                usage
                exit 0
                ;;
            --version)
                version
                exit 0
                ;;
            -v|--verbose)
                VERBOSE=true
                shift
                ;;
            -n|--dry-run)
                DRY_RUN=true
                shift
                ;;
            -*)
                print_error "Unknown option: $1"
                usage
                exit 1
                ;;
            *)
                if [ -z "$APPLICATION" ]; then
                    APPLICATION="$1"
                elif [ -z "$ARTIFACT_VAULT_URL" ]; then
                    ARTIFACT_VAULT_URL="$1"
                else
                    print_error "Too many arguments"
                    usage
                    exit 1
                fi
                shift
                ;;
        esac
    done
}

# Main function
main() {
    parse_args "$@"
    
    # Check required arguments
    if [ -z "$APPLICATION" ] || [ -z "$ARTIFACT_VAULT_URL" ]; then
        print_error "Missing required arguments"
        usage
        exit 1
    fi
    
    # Validate inputs
    if ! validate_url "$ARTIFACT_VAULT_URL"; then
        exit 1
    fi
    
    # Show configuration summary
    print_info "Artifact Vault Client Configuration"
    print_info "Application: $APPLICATION"
    print_info "Artifact Vault URL: $ARTIFACT_VAULT_URL"
    if [ "$DRY_RUN" = true ]; then
        print_info "Mode: Dry run (no changes will be made)"
    fi
    echo
    
    # Test connectivity (unless dry run)
    if [ "$DRY_RUN" = false ]; then
        test_connectivity "$ARTIFACT_VAULT_URL"
        echo
    fi
    
    # Configure the application
    configure_application "$APPLICATION" "$ARTIFACT_VAULT_URL"
    
    echo
    print_success "Configuration completed!"
    
    if [ "$DRY_RUN" = false ]; then
        print_info "Backup files are saved with suffix: $BACKUP_SUFFIX"
        print_info "To restore original configuration, restore from backup files"
    fi
}

# Run main function with all arguments
main "$@"